export enum ActionType {
    FETCH_ALL_START = 'FETCH_ALL_START',
    FETCH_ALL_COMPLETE = 'FETCH_ALL_COMPLETE',
    FETCH_ALL_ERROR = 'FETCH_ALL_ERROR',
    FETCH_SHOW_START = 'FETCH_SHOW_START',
    FETCH_SHOW_COMPLETE = 'FETCH_SHOW_COMPLETE',
    FETCH_SHOW_ERROR = 'FETCH_SHOW_ERROR',
}